export const constant = {
  API_URL: "https://immense-shelf-19793.herokuapp.com/api",
  LOADING: "LOADING",
  NONE: "NONE",
  FAILURE: "FAILURE",
  SUCCESS: "SUCCESS",
  //product
  GET_PURCHASED_PRODUCTS_SUCCESS: "GET_PURCHASED_PRODUCTS_SUCCESS",
  GET_PURCHASED_PRODUCTS_FAILURE: "GET_PURCHASED_PRODUCTS_FAILURE",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",
  GET_PRODUCT_REVIEW_SUCCESS: "GET_PRODUCT_REVIEW_SUCCESS",
  GET_PRODUCT_REVIEW_FAILURE: "GET_PRODUCT_REVIEW_FAILURE",
  //category
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",
  //user
  REQUEST_PHONE_CHECK: "REQUEST_PHONE_CHECK",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  REGIS_SUCCESS: "REGIS_SUCCESS",
  REGIS_FAILURE: "REGIS_FAILURE",
  //pop up
  NO_POPUP: "NO_POPUP",
  CHANGE_POPUP: "CHANGE_POPUP",
  PHONE_POPUP: "PHONE_POPUP",
  LOGIN_POPUP: "LOGIN_POPUP",
  REGIS_POPUP: "REGIS_POPOP",
  //message
  CLEAR_MESSAGE: "CLEAR_MESSAGE",
};
